# Generated by Django 3.2.4 on 2021-09-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='ip',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
