# Generated by Django 3.2.4 on 2021-09-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_settinglang_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lang',
            field=models.CharField(blank=True, choices=[], max_length=255),
        ),
        migrations.AlterField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(blank=True, choices=[], max_length=6),
        ),
    ]
