# Generated by Django 3.2.4 on 2021-09-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210910_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lang',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
