# Generated by Django 3.2.4 on 2021-09-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210911_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDDec_ar',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDDec_en',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDName_ar',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDName_en',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
