# Generated by Django 3.2.4 on 2021-09-12 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('product', '0006_auto_20210911_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDBrand_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDBrand_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDCategory_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDCategory_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDVandor_Name_ar',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDVandor_Name_en',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
