# Generated by Django 3.2.4 on 2021-08-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_i_agree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('default', 'default'), ('Pending', 'Pending'), ('Under_Process', 'Under_Process'), ('Completed', 'Completed'), ('Canceld', 'Canceld'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
    ]
